version: '3.8'

services:
  backend:
    container_name: portfolio-backend
    build:
      context: ./my-flask-backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=mysql.railway.internal  # l'hôte de la base de données Railway
      - MYSQL_PORT=43700  # le port de la base de données Railway
      - MYSQL_USER=root  # l'utilisateur de la base de données
      - MYSQL_PASSWORD=sJZJplXzZTroxulYDRHPaaMhGDsSOKtu # le mot de passe de la base de données
      - MYSQL_DB=railway # le nom de la base de données
    networks:
      - portfolio_app_network

  frontend:
    container_name: portfolio-frontend
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - portfolio_app_network

  nginx:
    container_name: portfolio-nginx
    image: nginx:latest
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "8081:80"
    depends_on:
      - frontend
    networks:
      - portfolio_app_network

networks:
  portfolio_app_network:
    driver: bridge
