version: '3.8'

services:
  backend:
    build:
      context: ./my-flask-backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=steve
      - MYSQL_DB=Portfolio
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: steve
      MYSQL_DATABASE: Portfolio
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
